export type SurahMeta = { n: number; name: string; arabic: string; translation: string; ayahs: number; juz: number; start: number; type: string };
export const surahList: SurahMeta[] = [
  {n:1,name:"Al-Faatiha",arabic:"ٱلْفَاتِحَةِ",translation:"The Opening",ayahs:7,juz:1,start:1,type:"Meccan"},
  {n:2,name:"Al-Baqara",arabic:"البَقَرَةِ",translation:"The Cow",ayahs:286,juz:1,start:8,type:"Medinan"},
  {n:3,name:"Aal-i-Imraan",arabic:"آلِ عِمۡرَانَ",translation:"The Family of Imraan",ayahs:200,juz:3,start:294,type:"Medinan"},
  {n:4,name:"An-Nisaa",arabic:"النِّسَاءِ",translation:"The Women",ayahs:176,juz:4,start:494,type:"Medinan"},
  {n:5,name:"Al-Maaida",arabic:"المَائـِدَةِ",translation:"The Table",ayahs:120,juz:6,start:670,type:"Medinan"},
  {n:6,name:"Al-An'aam",arabic:"الأَنۡعَامِ",translation:"The Cattle",ayahs:165,juz:7,start:790,type:"Meccan"},
  {n:7,name:"Al-A'raaf",arabic:"الأَعۡرَافِ",translation:"The Heights",ayahs:206,juz:8,start:955,type:"Meccan"},
  {n:8,name:"Al-Anfaal",arabic:"الأَنفَالِ",translation:"The Spoils of War",ayahs:75,juz:9,start:1161,type:"Medinan"},
  {n:9,name:"At-Tawba",arabic:"التَّوۡبَةِ",translation:"The Repentance",ayahs:129,juz:10,start:1236,type:"Medinan"},
  {n:10,name:"Yunus",arabic:"يُونُسَ",translation:"Jonas",ayahs:109,juz:11,start:1365,type:"Meccan"},
  {n:11,name:"Hud",arabic:"هُودٍ",translation:"Hud",ayahs:123,juz:11,start:1474,type:"Meccan"},
  {n:12,name:"Yusuf",arabic:"يُوسُفَ",translation:"Joseph",ayahs:111,juz:12,start:1597,type:"Meccan"},
  {n:13,name:"Ar-Ra'd",arabic:"الرَّعۡدِ",translation:"The Thunder",ayahs:43,juz:13,start:1708,type:"Medinan"},
  {n:14,name:"Ibrahim",arabic:"إِبۡرَاهِيمَ",translation:"Abraham",ayahs:52,juz:13,start:1751,type:"Meccan"},
  {n:15,name:"Al-Hijr",arabic:"الحِجۡرِ",translation:"The Rock",ayahs:99,juz:14,start:1803,type:"Meccan"},
  {n:16,name:"An-Nahl",arabic:"النَّحۡلِ",translation:"The Bee",ayahs:128,juz:14,start:1902,type:"Meccan"},
  {n:17,name:"Al-Israa",arabic:"الإِسۡرَاءِ",translation:"The Night Journey",ayahs:111,juz:15,start:2030,type:"Meccan"},
  {n:18,name:"Al-Kahf",arabic:"الكَهۡفِ",translation:"The Cave",ayahs:110,juz:15,start:2141,type:"Meccan"},
  {n:19,name:"Maryam",arabic:"مَرۡيَمَ",translation:"Mary",ayahs:98,juz:16,start:2251,type:"Meccan"},
  {n:20,name:"Taa-Haa",arabic:"طه",translation:"Taa-Haa",ayahs:135,juz:16,start:2349,type:"Meccan"},
  {n:21,name:"Al-Anbiyaa",arabic:"الأَنبِيَاءِ",translation:"The Prophets",ayahs:112,juz:17,start:2484,type:"Meccan"},
  {n:22,name:"Al-Hajj",arabic:"الحَجِّ",translation:"The Pilgrimage",ayahs:78,juz:17,start:2596,type:"Medinan"},
  {n:23,name:"Al-Muminoon",arabic:"المُؤۡمِنُونَ",translation:"The Believers",ayahs:118,juz:18,start:2674,type:"Meccan"},
  {n:24,name:"An-Noor",arabic:"النُّورِ",translation:"The Light",ayahs:64,juz:18,start:2792,type:"Medinan"},
  {n:25,name:"Al-Furqaan",arabic:"الفُرۡقَانِ",translation:"The Criterion",ayahs:77,juz:18,start:2856,type:"Meccan"},
  {n:26,name:"Ash-Shu'araa",arabic:"الشُّعَرَاءِ",translation:"The Poets",ayahs:227,juz:19,start:2933,type:"Meccan"},
  {n:27,name:"An-Naml",arabic:"النَّمۡلِ",translation:"The Ant",ayahs:93,juz:19,start:3160,type:"Meccan"},
  {n:28,name:"Al-Qasas",arabic:"القَصَصِ",translation:"The Stories",ayahs:88,juz:20,start:3253,type:"Meccan"},
  {n:29,name:"Al-Ankaboot",arabic:"العَنكَبُوتِ",translation:"The Spider",ayahs:69,juz:20,start:3341,type:"Meccan"},
  {n:30,name:"Ar-Room",arabic:"الرُّومِ",translation:"The Romans",ayahs:60,juz:21,start:3410,type:"Meccan"},
  {n:31,name:"Luqman",arabic:"لُقۡمَانَ",translation:"Luqman",ayahs:34,juz:21,start:3470,type:"Meccan"},
  {n:32,name:"As-Sajda",arabic:"السَّجۡدَةِ",translation:"The Prostration",ayahs:30,juz:21,start:3504,type:"Meccan"},
  {n:33,name:"Al-Ahzaab",arabic:"الأَحۡزَابِ",translation:"The Clans",ayahs:73,juz:21,start:3534,type:"Medinan"},
  {n:34,name:"Saba",arabic:"سَبَإٍ",translation:"Sheba",ayahs:54,juz:22,start:3607,type:"Meccan"},
  {n:35,name:"Faatir",arabic:"فَاطِرٍ",translation:"The Originator",ayahs:45,juz:22,start:3661,type:"Meccan"},
  {n:36,name:"Yaseen",arabic:"يسٓ",translation:"Yaseen",ayahs:83,juz:22,start:3706,type:"Meccan"},
  {n:37,name:"As-Saaffaat",arabic:"الصَّافَّاتِ",translation:"Those drawn up in Ranks",ayahs:182,juz:23,start:3789,type:"Meccan"},
  {n:38,name:"Saad",arabic:"صٓ",translation:"The letter Saad",ayahs:88,juz:23,start:3971,type:"Meccan"},
  {n:39,name:"Az-Zumar",arabic:"الزُّمَرِ",translation:"The Groups",ayahs:75,juz:23,start:4059,type:"Meccan"},
  {n:40,name:"Ghafir",arabic:"غَافِرٍ",translation:"The Forgiver",ayahs:85,juz:24,start:4134,type:"Meccan"},
  {n:41,name:"Fussilat",arabic:"فُصِّلَتۡ",translation:"Explained in detail",ayahs:54,juz:24,start:4219,type:"Meccan"},
  {n:42,name:"Ash-Shura",arabic:"الشُّورَىٰ",translation:"Consultation",ayahs:53,juz:25,start:4273,type:"Meccan"},
  {n:43,name:"Az-Zukhruf",arabic:"الزُّخۡرُفِ",translation:"Ornaments of gold",ayahs:89,juz:25,start:4326,type:"Meccan"},
  {n:44,name:"Ad-Dukhaan",arabic:"الدُّخَانِ",translation:"The Smoke",ayahs:59,juz:25,start:4415,type:"Meccan"},
  {n:45,name:"Al-Jaathiya",arabic:"الجَاثِيَةِ",translation:"Crouching",ayahs:37,juz:25,start:4474,type:"Meccan"},
  {n:46,name:"Al-Ahqaf",arabic:"الأَحۡقَافِ",translation:"The Dunes",ayahs:35,juz:26,start:4511,type:"Meccan"},
  {n:47,name:"Muhammad",arabic:"مُحَمَّدٍ",translation:"Muhammad",ayahs:38,juz:26,start:4546,type:"Medinan"},
  {n:48,name:"Al-Fath",arabic:"الفَتۡحِ",translation:"The Victory",ayahs:29,juz:26,start:4584,type:"Medinan"},
  {n:49,name:"Al-Hujuraat",arabic:"الحُجُرَاتِ",translation:"The Inner Apartments",ayahs:18,juz:26,start:4613,type:"Medinan"},
  {n:50,name:"Qaaf",arabic:"قٓ",translation:"The letter Qaaf",ayahs:45,juz:26,start:4631,type:"Meccan"},
  {n:51,name:"Adh-Dhaariyat",arabic:"الذَّارِيَاتِ",translation:"The Winnowing Winds",ayahs:60,juz:26,start:4676,type:"Meccan"},
  {n:52,name:"At-Tur",arabic:"الطُّورِ",translation:"The Mount",ayahs:49,juz:27,start:4736,type:"Meccan"},
  {n:53,name:"An-Najm",arabic:"النَّجۡمِ",translation:"The Star",ayahs:62,juz:27,start:4785,type:"Meccan"},
  {n:54,name:"Al-Qamar",arabic:"القَمَرِ",translation:"The Moon",ayahs:55,juz:27,start:4847,type:"Meccan"},
  {n:55,name:"Ar-Rahmaan",arabic:"الرَّحۡمَٰن",translation:"The Beneficent",ayahs:78,juz:27,start:4902,type:"Medinan"},
  {n:56,name:"Al-Waaqia",arabic:"الوَاقِعَةِ",translation:"The Inevitable",ayahs:96,juz:27,start:4980,type:"Meccan"},
  {n:57,name:"Al-Hadid",arabic:"الحَدِيدِ",translation:"The Iron",ayahs:29,juz:27,start:5076,type:"Medinan"},
  {n:58,name:"Al-Mujaadila",arabic:"المُجَادلَةِ",translation:"The Pleading Woman",ayahs:22,juz:28,start:5105,type:"Medinan"},
  {n:59,name:"Al-Hashr",arabic:"الحَشۡرِ",translation:"The Exile",ayahs:24,juz:28,start:5127,type:"Medinan"},
  {n:60,name:"Al-Mumtahana",arabic:"المُمۡتَحنَةِ",translation:"She that is to be examined",ayahs:13,juz:28,start:5151,type:"Medinan"},
  {n:61,name:"As-Saff",arabic:"الصَّفِّ",translation:"The Ranks",ayahs:14,juz:28,start:5164,type:"Medinan"},
  {n:62,name:"Al-Jumu'a",arabic:"الجُمُعَةِ",translation:"Friday",ayahs:11,juz:28,start:5178,type:"Medinan"},
  {n:63,name:"Al-Munaafiqoon",arabic:"المُنَافِقُونَ",translation:"The Hypocrites",ayahs:11,juz:28,start:5189,type:"Medinan"},
  {n:64,name:"At-Taghaabun",arabic:"التَّغَابُنِ",translation:"Mutual Disillusion",ayahs:18,juz:28,start:5200,type:"Medinan"},
  {n:65,name:"At-Talaaq",arabic:"الطَّلَاقِ",translation:"Divorce",ayahs:12,juz:28,start:5218,type:"Medinan"},
  {n:66,name:"At-Tahrim",arabic:"التَّحۡرِيمِ",translation:"The Prohibition",ayahs:12,juz:28,start:5230,type:"Medinan"},
  {n:67,name:"Al-Mulk",arabic:"المُلۡكِ",translation:"The Sovereignty",ayahs:30,juz:29,start:5242,type:"Meccan"},
  {n:68,name:"Al-Qalam",arabic:"القَلَمِ",translation:"The Pen",ayahs:52,juz:29,start:5272,type:"Meccan"},
  {n:69,name:"Al-Haaqqa",arabic:"الحَاقَّةِ",translation:"The Reality",ayahs:52,juz:29,start:5324,type:"Meccan"},
  {n:70,name:"Al-Ma'aarij",arabic:"المَعَارِجِ",translation:"The Ascending Stairways",ayahs:44,juz:29,start:5376,type:"Meccan"},
  {n:71,name:"Nooh",arabic:"نُوحٍ",translation:"Noah",ayahs:28,juz:29,start:5420,type:"Meccan"},
  {n:72,name:"Al-Jinn",arabic:"الجِنِّ",translation:"The Jinn",ayahs:28,juz:29,start:5448,type:"Meccan"},
  {n:73,name:"Al-Muzzammil",arabic:"المُزَّمِّلِ",translation:"The Enshrouded One",ayahs:20,juz:29,start:5476,type:"Meccan"},
  {n:74,name:"Al-Muddaththir",arabic:"المُدَّثِّرِ",translation:"The Cloaked One",ayahs:56,juz:29,start:5496,type:"Meccan"},
  {n:75,name:"Al-Qiyaama",arabic:"القِيَامَةِ",translation:"The Resurrection",ayahs:40,juz:29,start:5552,type:"Meccan"},
  {n:76,name:"Al-Insaan",arabic:"الإِنسَانِ",translation:"Man",ayahs:31,juz:29,start:5592,type:"Medinan"},
  {n:77,name:"Al-Mursalaat",arabic:"المُرۡسَلَاتِ",translation:"The Emissaries",ayahs:50,juz:29,start:5623,type:"Meccan"},
  {n:78,name:"An-Naba",arabic:"النَّبَإِ",translation:"The Announcement",ayahs:40,juz:30,start:5673,type:"Meccan"},
  {n:79,name:"An-Naazi'aat",arabic:"النَّازِعَاتِ",translation:"Those who drag forth",ayahs:46,juz:30,start:5713,type:"Meccan"},
  {n:80,name:"Abasa",arabic:"عَبَسَ",translation:"He frowned",ayahs:42,juz:30,start:5759,type:"Meccan"},
  {n:81,name:"At-Takwir",arabic:"التَّكۡوِيرِ",translation:"The Overthrowing",ayahs:29,juz:30,start:5801,type:"Meccan"},
  {n:82,name:"Al-Infitaar",arabic:"الانفِطَارِ",translation:"The Cleaving",ayahs:19,juz:30,start:5830,type:"Meccan"},
  {n:83,name:"Al-Mutaffifin",arabic:"المُطَفِّفِينَ",translation:"Defrauding",ayahs:36,juz:30,start:5849,type:"Meccan"},
  {n:84,name:"Al-Inshiqaaq",arabic:"الانشِقَاقِ",translation:"The Splitting Open",ayahs:25,juz:30,start:5885,type:"Meccan"},
  {n:85,name:"Al-Burooj",arabic:"البُرُوجِ",translation:"The Constellations",ayahs:22,juz:30,start:5910,type:"Meccan"},
  {n:86,name:"At-Taariq",arabic:"الطَّارِقِ",translation:"The Morning Star",ayahs:17,juz:30,start:5932,type:"Meccan"},
  {n:87,name:"Al-A'laa",arabic:"الأَعۡلَىٰ",translation:"The Most High",ayahs:19,juz:30,start:5949,type:"Meccan"},
  {n:88,name:"Al-Ghaashiya",arabic:"الغَاشِيَةِ",translation:"The Overwhelming",ayahs:26,juz:30,start:5968,type:"Meccan"},
  {n:89,name:"Al-Fajr",arabic:"الفَجۡرِ",translation:"The Dawn",ayahs:30,juz:30,start:5994,type:"Meccan"},
  {n:90,name:"Al-Balad",arabic:"البَلَدِ",translation:"The City",ayahs:20,juz:30,start:6024,type:"Meccan"},
  {n:91,name:"Ash-Shams",arabic:"الشَّمۡسِ",translation:"The Sun",ayahs:15,juz:30,start:6044,type:"Meccan"},
  {n:92,name:"Al-Lail",arabic:"اللَّيۡلِ",translation:"The Night",ayahs:21,juz:30,start:6059,type:"Meccan"},
  {n:93,name:"Ad-Dhuhaa",arabic:"الضُّحَىٰ",translation:"The Morning Hours",ayahs:11,juz:30,start:6080,type:"Meccan"},
  {n:94,name:"Ash-Sharh",arabic:"الشَّرۡحِ",translation:"The Consolation",ayahs:8,juz:30,start:6091,type:"Meccan"},
  {n:95,name:"At-Tin",arabic:"التِّينِ",translation:"The Fig",ayahs:8,juz:30,start:6099,type:"Meccan"},
  {n:96,name:"Al-Alaq",arabic:"العَلَقِ",translation:"The Clot",ayahs:19,juz:30,start:6107,type:"Meccan"},
  {n:97,name:"Al-Qadr",arabic:"القَدۡرِ",translation:"The Power, Fate",ayahs:5,juz:30,start:6126,type:"Meccan"},
  {n:98,name:"Al-Bayyina",arabic:"البَيِّنَةِ",translation:"The Evidence",ayahs:8,juz:30,start:6131,type:"Medinan"},
  {n:99,name:"Az-Zalzala",arabic:"الزَّلۡزَلَةِ",translation:"The Earthquake",ayahs:8,juz:30,start:6139,type:"Medinan"},
  {n:100,name:"Al-Aadiyaat",arabic:"العَادِيَاتِ",translation:"The Chargers",ayahs:11,juz:30,start:6147,type:"Meccan"},
  {n:101,name:"Al-Qaari'a",arabic:"القَارِعَةِ",translation:"The Calamity",ayahs:11,juz:30,start:6158,type:"Meccan"},
  {n:102,name:"At-Takaathur",arabic:"التَّكَاثُرِ",translation:"Competition",ayahs:8,juz:30,start:6169,type:"Meccan"},
  {n:103,name:"Al-Asr",arabic:"العَصۡرِ",translation:"The Declining Day, Epoch",ayahs:3,juz:30,start:6177,type:"Meccan"},
  {n:104,name:"Al-Humaza",arabic:"الهُمَزَةِ",translation:"The Traducer",ayahs:9,juz:30,start:6180,type:"Meccan"},
  {n:105,name:"Al-Fil",arabic:"الفِيلِ",translation:"The Elephant",ayahs:5,juz:30,start:6189,type:"Meccan"},
  {n:106,name:"Quraish",arabic:"قُرَيۡشٍ",translation:"Quraysh",ayahs:4,juz:30,start:6194,type:"Meccan"},
  {n:107,name:"Al-Maa'un",arabic:"المَاعُونِ",translation:"Almsgiving",ayahs:7,juz:30,start:6198,type:"Meccan"},
  {n:108,name:"Al-Kawthar",arabic:"الكَوۡثَرِ",translation:"Abundance",ayahs:3,juz:30,start:6205,type:"Meccan"},
  {n:109,name:"Al-Kaafiroon",arabic:"الكَافِرُونَ",translation:"The Disbelievers",ayahs:6,juz:30,start:6208,type:"Meccan"},
  {n:110,name:"An-Nasr",arabic:"النَّصۡرِ",translation:"Divine Support",ayahs:3,juz:30,start:6214,type:"Medinan"},
  {n:111,name:"Al-Masad",arabic:"المَسَدِ",translation:"The Palm Fibre",ayahs:5,juz:30,start:6217,type:"Meccan"},
  {n:112,name:"Al-Ikhlaas",arabic:"الإِخۡلَاصِ",translation:"Sincerity",ayahs:4,juz:30,start:6222,type:"Meccan"},
  {n:113,name:"Al-Falaq",arabic:"الفَلَقِ",translation:"The Dawn",ayahs:5,juz:30,start:6226,type:"Meccan"},
  {n:114,name:"An-Naas",arabic:"النَّاسِ",translation:"Mankind",ayahs:6,juz:30,start:6231,type:"Meccan"},
];
