/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IlmbotRouteImport } from './routes/ilmbot'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as RamadanRouteImport } from './routes/ramadan'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShareRouteImport } from './routes/share'
import { Route as StoreRouteImport } from './routes/store'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as WisdomRouteImport } from './routes/wisdom'
import { Route as ChallengeDuelRouteImport } from './routes/challenge.duel'
import { Route as ChallengeResultsRouteImport } from './routes/challenge.results'
import { Route as ChallengeSetupRouteImport } from './routes/challenge.setup'
import { Route as ChallengeWaitingRouteImport } from './routes/challenge.waiting'
import { Route as FriendsIndexRouteImport } from './routes/friends.index'
import { Route as FriendsFriendIdRouteImport } from './routes/friends.$friendId'
import { Route as HalaqahIndexRouteImport } from './routes/halaqah.index'
import { Route as HalaqahGameRouteImport } from './routes/halaqah.game'
import { Route as HalaqahResultsRouteImport } from './routes/halaqah.results'
import { Route as HifzIndexRouteImport } from './routes/hifz.index'
import { Route as HifzCompleteRouteImport } from './routes/hifz.complete'
import { Route as HifzReviewRouteImport } from './routes/hifz.review'
import { Route as HifzSessionRouteImport } from './routes/hifz.session'
import { Route as HomeQuestRouteImport } from './routes/home.quest'
import { Route as LibraryIndexRouteImport } from './routes/library.index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as OnboardingAssessmentRouteImport } from './routes/onboarding.assessment'
import { Route as OnboardingAvatarRouteImport } from './routes/onboarding.avatar'
import { Route as OnboardingCarouselRouteImport } from './routes/onboarding.carousel'
import { Route as OnboardingCheckEmailRouteImport } from './routes/onboarding.check-email'
import { Route as OnboardingDobRouteImport } from './routes/onboarding.dob'
import { Route as OnboardingForgotRouteImport } from './routes/onboarding.forgot'
import { Route as OnboardingGatewayRouteImport } from './routes/onboarding.gateway'
import { Route as OnboardingInterestsRouteImport } from './routes/onboarding.interests'
import { Route as OnboardingLanguageRouteImport } from './routes/onboarding.language'
import { Route as OnboardingLoginRouteImport } from './routes/onboarding.login'
import { Route as OnboardingPasswordRouteImport } from './routes/onboarding.password'
import { Route as OnboardingResetRouteImport } from './routes/onboarding.reset'
import { Route as OnboardingSignupRouteImport } from './routes/onboarding.signup'
import { Route as OnboardingVerifyRouteImport } from './routes/onboarding.verify'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingZoneRouteImport } from './routes/onboarding.zone'
import { Route as PlayIndexRouteImport } from './routes/play.index'
import { Route as PlayDifficultyRouteImport } from './routes/play.difficulty'
import { Route as PlayLobbyRouteImport } from './routes/play.lobby'
import { Route as PlayTopicsRouteImport } from './routes/play.topics'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as QuestsQuestIdRouteImport } from './routes/quests.$questId'
import { Route as QuestsCompleteRouteImport } from './routes/quests.complete'
import { Route as QuizIndexRouteImport } from './routes/quiz.index'
import { Route as QuizResultsRouteImport } from './routes/quiz.results'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IlmbotRoute = IlmbotRouteImport.update({
  id: '/ilmbot',
  path: '/ilmbot',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const RamadanRoute = RamadanRouteImport.update({
  id: '/ramadan',
  path: '/ramadan',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const WisdomRoute = WisdomRouteImport.update({
  id: '/wisdom',
  path: '/wisdom',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeDuelRoute = ChallengeDuelRouteImport.update({
  id: '/challenge/duel',
  path: '/challenge/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeResultsRoute = ChallengeResultsRouteImport.update({
  id: '/challenge/results',
  path: '/challenge/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeSetupRoute = ChallengeSetupRouteImport.update({
  id: '/challenge/setup',
  path: '/challenge/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeWaitingRoute = ChallengeWaitingRouteImport.update({
  id: '/challenge/waiting',
  path: '/challenge/waiting',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: '/friends/',
  path: '/friends/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsFriendIdRoute = FriendsFriendIdRouteImport.update({
  id: '/friends/$friendId',
  path: '/friends/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const HalaqahIndexRoute = HalaqahIndexRouteImport.update({
  id: '/halaqah/',
  path: '/halaqah/',
  getParentRoute: () => rootRouteImport,
} as any)
const HalaqahGameRoute = HalaqahGameRouteImport.update({
  id: '/halaqah/game',
  path: '/halaqah/game',
  getParentRoute: () => rootRouteImport,
} as any)
const HalaqahResultsRoute = HalaqahResultsRouteImport.update({
  id: '/halaqah/results',
  path: '/halaqah/results',
  getParentRoute: () => rootRouteImport,
} as any)
const HifzIndexRoute = HifzIndexRouteImport.update({
  id: '/hifz/',
  path: '/hifz/',
  getParentRoute: () => rootRouteImport,
} as any)
const HifzCompleteRoute = HifzCompleteRouteImport.update({
  id: '/hifz/complete',
  path: '/hifz/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const HifzReviewRoute = HifzReviewRouteImport.update({
  id: '/hifz/review',
  path: '/hifz/review',
  getParentRoute: () => rootRouteImport,
} as any)
const HifzSessionRoute = HifzSessionRouteImport.update({
  id: '/hifz/session',
  path: '/hifz/session',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeQuestRoute = HomeQuestRouteImport.update({
  id: '/quest',
  path: '/quest',
  getParentRoute: () => HomeRoute,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/library/$slug',
  path: '/library/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAssessmentRoute = OnboardingAssessmentRouteImport.update({
  id: '/onboarding/assessment',
  path: '/onboarding/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAvatarRoute = OnboardingAvatarRouteImport.update({
  id: '/onboarding/avatar',
  path: '/onboarding/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCarouselRoute = OnboardingCarouselRouteImport.update({
  id: '/onboarding/carousel',
  path: '/onboarding/carousel',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCheckEmailRoute = OnboardingCheckEmailRouteImport.update({
  id: '/onboarding/check-email',
  path: '/onboarding/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDobRoute = OnboardingDobRouteImport.update({
  id: '/onboarding/dob',
  path: '/onboarding/dob',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingForgotRoute = OnboardingForgotRouteImport.update({
  id: '/onboarding/forgot',
  path: '/onboarding/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGatewayRoute = OnboardingGatewayRouteImport.update({
  id: '/onboarding/gateway',
  path: '/onboarding/gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInterestsRoute = OnboardingInterestsRouteImport.update({
  id: '/onboarding/interests',
  path: '/onboarding/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLanguageRoute = OnboardingLanguageRouteImport.update({
  id: '/onboarding/language',
  path: '/onboarding/language',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLoginRoute = OnboardingLoginRouteImport.update({
  id: '/onboarding/login',
  path: '/onboarding/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPasswordRoute = OnboardingPasswordRouteImport.update({
  id: '/onboarding/password',
  path: '/onboarding/password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingResetRoute = OnboardingResetRouteImport.update({
  id: '/onboarding/reset',
  path: '/onboarding/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignupRoute = OnboardingSignupRouteImport.update({
  id: '/onboarding/signup',
  path: '/onboarding/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVerifyRoute = OnboardingVerifyRouteImport.update({
  id: '/onboarding/verify',
  path: '/onboarding/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingZoneRoute = OnboardingZoneRouteImport.update({
  id: '/onboarding/zone',
  path: '/onboarding/zone',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayIndexRoute = PlayIndexRouteImport.update({
  id: '/play/',
  path: '/play/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDifficultyRoute = PlayDifficultyRouteImport.update({
  id: '/play/difficulty',
  path: '/play/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLobbyRoute = PlayLobbyRouteImport.update({
  id: '/play/lobby',
  path: '/play/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayTopicsRoute = PlayTopicsRouteImport.update({
  id: '/play/topics',
  path: '/play/topics',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestIdRoute = QuestsQuestIdRouteImport.update({
  id: '/quests/$questId',
  path: '/quests/$questId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsCompleteRoute = QuestsCompleteRouteImport.update({
  id: '/quests/complete',
  path: '/quests/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizIndexRoute = QuizIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => QuizRoute,
} as any)
const QuizResultsRoute = QuizResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => QuizRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/error': typeof ErrorRoute
  '/home': typeof HomeRouteWithChildren
  '/ilmbot': typeof IlmbotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/ramadan': typeof RamadanRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/wisdom': typeof WisdomRoute
  '/challenge/duel': typeof ChallengeDuelRoute
  '/challenge/results': typeof ChallengeResultsRoute
  '/challenge/setup': typeof ChallengeSetupRoute
  '/challenge/waiting': typeof ChallengeWaitingRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/halaqah/game': typeof HalaqahGameRoute
  '/halaqah/results': typeof HalaqahResultsRoute
  '/hifz/complete': typeof HifzCompleteRoute
  '/hifz/review': typeof HifzReviewRoute
  '/hifz/session': typeof HifzSessionRoute
  '/home/quest': typeof HomeQuestRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/carousel': typeof OnboardingCarouselRoute
  '/onboarding/check-email': typeof OnboardingCheckEmailRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/forgot': typeof OnboardingForgotRoute
  '/onboarding/gateway': typeof OnboardingGatewayRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/password': typeof OnboardingPasswordRoute
  '/onboarding/reset': typeof OnboardingResetRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/zone': typeof OnboardingZoneRoute
  '/play/difficulty': typeof PlayDifficultyRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/topics': typeof PlayTopicsRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/complete': typeof QuestsCompleteRoute
  '/quiz/results': typeof QuizResultsRoute
  '/friends/': typeof FriendsIndexRoute
  '/halaqah/': typeof HalaqahIndexRoute
  '/hifz/': typeof HifzIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/play/': typeof PlayIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/error': typeof ErrorRoute
  '/home': typeof HomeRouteWithChildren
  '/ilmbot': typeof IlmbotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/ramadan': typeof RamadanRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/wisdom': typeof WisdomRoute
  '/challenge/duel': typeof ChallengeDuelRoute
  '/challenge/results': typeof ChallengeResultsRoute
  '/challenge/setup': typeof ChallengeSetupRoute
  '/challenge/waiting': typeof ChallengeWaitingRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/halaqah/game': typeof HalaqahGameRoute
  '/halaqah/results': typeof HalaqahResultsRoute
  '/hifz/complete': typeof HifzCompleteRoute
  '/hifz/review': typeof HifzReviewRoute
  '/hifz/session': typeof HifzSessionRoute
  '/home/quest': typeof HomeQuestRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/carousel': typeof OnboardingCarouselRoute
  '/onboarding/check-email': typeof OnboardingCheckEmailRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/forgot': typeof OnboardingForgotRoute
  '/onboarding/gateway': typeof OnboardingGatewayRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/password': typeof OnboardingPasswordRoute
  '/onboarding/reset': typeof OnboardingResetRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/zone': typeof OnboardingZoneRoute
  '/play/difficulty': typeof PlayDifficultyRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/topics': typeof PlayTopicsRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/complete': typeof QuestsCompleteRoute
  '/quiz/results': typeof QuizResultsRoute
  '/friends': typeof FriendsIndexRoute
  '/halaqah': typeof HalaqahIndexRoute
  '/hifz': typeof HifzIndexRoute
  '/library': typeof LibraryIndexRoute
  '/play': typeof PlayIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/quiz': typeof QuizIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/bookmarks': typeof BookmarksRoute
  '/error': typeof ErrorRoute
  '/home': typeof HomeRouteWithChildren
  '/ilmbot': typeof IlmbotRoute
  '/leaderboard': typeof LeaderboardRoute
  '/notifications': typeof NotificationsRoute
  '/offline': typeof OfflineRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/quiz': typeof QuizRouteWithChildren
  '/ramadan': typeof RamadanRoute
  '/settings': typeof SettingsRoute
  '/share': typeof ShareRoute
  '/store': typeof StoreRoute
  '/wallet': typeof WalletRoute
  '/wisdom': typeof WisdomRoute
  '/challenge/duel': typeof ChallengeDuelRoute
  '/challenge/results': typeof ChallengeResultsRoute
  '/challenge/setup': typeof ChallengeSetupRoute
  '/challenge/waiting': typeof ChallengeWaitingRoute
  '/friends/$friendId': typeof FriendsFriendIdRoute
  '/halaqah/game': typeof HalaqahGameRoute
  '/halaqah/results': typeof HalaqahResultsRoute
  '/hifz/complete': typeof HifzCompleteRoute
  '/hifz/review': typeof HifzReviewRoute
  '/hifz/session': typeof HifzSessionRoute
  '/home/quest': typeof HomeQuestRoute
  '/library/$slug': typeof LibrarySlugRoute
  '/onboarding/assessment': typeof OnboardingAssessmentRoute
  '/onboarding/avatar': typeof OnboardingAvatarRoute
  '/onboarding/carousel': typeof OnboardingCarouselRoute
  '/onboarding/check-email': typeof OnboardingCheckEmailRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/forgot': typeof OnboardingForgotRoute
  '/onboarding/gateway': typeof OnboardingGatewayRoute
  '/onboarding/interests': typeof OnboardingInterestsRoute
  '/onboarding/language': typeof OnboardingLanguageRoute
  '/onboarding/login': typeof OnboardingLoginRoute
  '/onboarding/password': typeof OnboardingPasswordRoute
  '/onboarding/reset': typeof OnboardingResetRoute
  '/onboarding/signup': typeof OnboardingSignupRoute
  '/onboarding/verify': typeof OnboardingVerifyRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/zone': typeof OnboardingZoneRoute
  '/play/difficulty': typeof PlayDifficultyRoute
  '/play/lobby': typeof PlayLobbyRoute
  '/play/topics': typeof PlayTopicsRoute
  '/quests/$questId': typeof QuestsQuestIdRoute
  '/quests/complete': typeof QuestsCompleteRoute
  '/quiz/results': typeof QuizResultsRoute
  '/friends/': typeof FriendsIndexRoute
  '/halaqah/': typeof HalaqahIndexRoute
  '/hifz/': typeof HifzIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/play/': typeof PlayIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/quiz/': typeof QuizIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/bookmarks'
    | '/error'
    | '/home'
    | '/ilmbot'
    | '/leaderboard'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ramadan'
    | '/settings'
    | '/share'
    | '/store'
    | '/wallet'
    | '/wisdom'
    | '/challenge/duel'
    | '/challenge/results'
    | '/challenge/setup'
    | '/challenge/waiting'
    | '/friends/$friendId'
    | '/halaqah/game'
    | '/halaqah/results'
    | '/hifz/complete'
    | '/hifz/review'
    | '/hifz/session'
    | '/home/quest'
    | '/library/$slug'
    | '/onboarding/assessment'
    | '/onboarding/avatar'
    | '/onboarding/carousel'
    | '/onboarding/check-email'
    | '/onboarding/dob'
    | '/onboarding/forgot'
    | '/onboarding/gateway'
    | '/onboarding/interests'
    | '/onboarding/language'
    | '/onboarding/login'
    | '/onboarding/password'
    | '/onboarding/reset'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/onboarding/zone'
    | '/play/difficulty'
    | '/play/lobby'
    | '/play/topics'
    | '/quests/$questId'
    | '/quests/complete'
    | '/quiz/results'
    | '/friends/'
    | '/halaqah/'
    | '/hifz/'
    | '/library/'
    | '/play/'
    | '/quests/'
    | '/quiz/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/bookmarks'
    | '/error'
    | '/home'
    | '/ilmbot'
    | '/leaderboard'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/progress'
    | '/ramadan'
    | '/settings'
    | '/share'
    | '/store'
    | '/wallet'
    | '/wisdom'
    | '/challenge/duel'
    | '/challenge/results'
    | '/challenge/setup'
    | '/challenge/waiting'
    | '/friends/$friendId'
    | '/halaqah/game'
    | '/halaqah/results'
    | '/hifz/complete'
    | '/hifz/review'
    | '/hifz/session'
    | '/home/quest'
    | '/library/$slug'
    | '/onboarding/assessment'
    | '/onboarding/avatar'
    | '/onboarding/carousel'
    | '/onboarding/check-email'
    | '/onboarding/dob'
    | '/onboarding/forgot'
    | '/onboarding/gateway'
    | '/onboarding/interests'
    | '/onboarding/language'
    | '/onboarding/login'
    | '/onboarding/password'
    | '/onboarding/reset'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/onboarding/zone'
    | '/play/difficulty'
    | '/play/lobby'
    | '/play/topics'
    | '/quests/$questId'
    | '/quests/complete'
    | '/quiz/results'
    | '/friends'
    | '/halaqah'
    | '/hifz'
    | '/library'
    | '/play'
    | '/quests'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/bookmarks'
    | '/error'
    | '/home'
    | '/ilmbot'
    | '/leaderboard'
    | '/notifications'
    | '/offline'
    | '/profile'
    | '/progress'
    | '/quiz'
    | '/ramadan'
    | '/settings'
    | '/share'
    | '/store'
    | '/wallet'
    | '/wisdom'
    | '/challenge/duel'
    | '/challenge/results'
    | '/challenge/setup'
    | '/challenge/waiting'
    | '/friends/$friendId'
    | '/halaqah/game'
    | '/halaqah/results'
    | '/hifz/complete'
    | '/hifz/review'
    | '/hifz/session'
    | '/home/quest'
    | '/library/$slug'
    | '/onboarding/assessment'
    | '/onboarding/avatar'
    | '/onboarding/carousel'
    | '/onboarding/check-email'
    | '/onboarding/dob'
    | '/onboarding/forgot'
    | '/onboarding/gateway'
    | '/onboarding/interests'
    | '/onboarding/language'
    | '/onboarding/login'
    | '/onboarding/password'
    | '/onboarding/reset'
    | '/onboarding/signup'
    | '/onboarding/verify'
    | '/onboarding/welcome'
    | '/onboarding/zone'
    | '/play/difficulty'
    | '/play/lobby'
    | '/play/topics'
    | '/quests/$questId'
    | '/quests/complete'
    | '/quiz/results'
    | '/friends/'
    | '/halaqah/'
    | '/hifz/'
    | '/library/'
    | '/play/'
    | '/quests/'
    | '/quiz/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  BookmarksRoute: typeof BookmarksRoute
  ErrorRoute: typeof ErrorRoute
  HomeRoute: typeof HomeRouteWithChildren
  IlmbotRoute: typeof IlmbotRoute
  LeaderboardRoute: typeof LeaderboardRoute
  NotificationsRoute: typeof NotificationsRoute
  OfflineRoute: typeof OfflineRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  QuizRoute: typeof QuizRouteWithChildren
  RamadanRoute: typeof RamadanRoute
  SettingsRoute: typeof SettingsRoute
  ShareRoute: typeof ShareRoute
  StoreRoute: typeof StoreRoute
  WalletRoute: typeof WalletRoute
  WisdomRoute: typeof WisdomRoute
  ChallengeDuelRoute: typeof ChallengeDuelRoute
  ChallengeResultsRoute: typeof ChallengeResultsRoute
  ChallengeSetupRoute: typeof ChallengeSetupRoute
  ChallengeWaitingRoute: typeof ChallengeWaitingRoute
  FriendsFriendIdRoute: typeof FriendsFriendIdRoute
  HalaqahGameRoute: typeof HalaqahGameRoute
  HalaqahResultsRoute: typeof HalaqahResultsRoute
  HifzCompleteRoute: typeof HifzCompleteRoute
  HifzReviewRoute: typeof HifzReviewRoute
  HifzSessionRoute: typeof HifzSessionRoute
  LibrarySlugRoute: typeof LibrarySlugRoute
  OnboardingAssessmentRoute: typeof OnboardingAssessmentRoute
  OnboardingAvatarRoute: typeof OnboardingAvatarRoute
  OnboardingCarouselRoute: typeof OnboardingCarouselRoute
  OnboardingCheckEmailRoute: typeof OnboardingCheckEmailRoute
  OnboardingDobRoute: typeof OnboardingDobRoute
  OnboardingForgotRoute: typeof OnboardingForgotRoute
  OnboardingGatewayRoute: typeof OnboardingGatewayRoute
  OnboardingInterestsRoute: typeof OnboardingInterestsRoute
  OnboardingLanguageRoute: typeof OnboardingLanguageRoute
  OnboardingLoginRoute: typeof OnboardingLoginRoute
  OnboardingPasswordRoute: typeof OnboardingPasswordRoute
  OnboardingResetRoute: typeof OnboardingResetRoute
  OnboardingSignupRoute: typeof OnboardingSignupRoute
  OnboardingVerifyRoute: typeof OnboardingVerifyRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingZoneRoute: typeof OnboardingZoneRoute
  PlayDifficultyRoute: typeof PlayDifficultyRoute
  PlayLobbyRoute: typeof PlayLobbyRoute
  PlayTopicsRoute: typeof PlayTopicsRoute
  QuestsQuestIdRoute: typeof QuestsQuestIdRoute
  QuestsCompleteRoute: typeof QuestsCompleteRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
  HalaqahIndexRoute: typeof HalaqahIndexRoute
  HifzIndexRoute: typeof HifzIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  PlayIndexRoute: typeof PlayIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ilmbot': {
      id: '/ilmbot'
      path: '/ilmbot'
      fullPath: '/ilmbot'
      preLoaderRoute: typeof IlmbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ramadan': {
      id: '/ramadan'
      path: '/ramadan'
      fullPath: '/ramadan'
      preLoaderRoute: typeof RamadanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wisdom': {
      id: '/wisdom'
      path: '/wisdom'
      fullPath: '/wisdom'
      preLoaderRoute: typeof WisdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/duel': {
      id: '/challenge/duel'
      path: '/challenge/duel'
      fullPath: '/challenge/duel'
      preLoaderRoute: typeof ChallengeDuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/results': {
      id: '/challenge/results'
      path: '/challenge/results'
      fullPath: '/challenge/results'
      preLoaderRoute: typeof ChallengeResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/setup': {
      id: '/challenge/setup'
      path: '/challenge/setup'
      fullPath: '/challenge/setup'
      preLoaderRoute: typeof ChallengeSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/waiting': {
      id: '/challenge/waiting'
      path: '/challenge/waiting'
      fullPath: '/challenge/waiting'
      preLoaderRoute: typeof ChallengeWaitingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/': {
      id: '/friends/'
      path: '/friends'
      fullPath: '/friends/'
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/$friendId': {
      id: '/friends/$friendId'
      path: '/friends/$friendId'
      fullPath: '/friends/$friendId'
      preLoaderRoute: typeof FriendsFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaqah/': {
      id: '/halaqah/'
      path: '/halaqah'
      fullPath: '/halaqah/'
      preLoaderRoute: typeof HalaqahIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaqah/game': {
      id: '/halaqah/game'
      path: '/halaqah/game'
      fullPath: '/halaqah/game'
      preLoaderRoute: typeof HalaqahGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaqah/results': {
      id: '/halaqah/results'
      path: '/halaqah/results'
      fullPath: '/halaqah/results'
      preLoaderRoute: typeof HalaqahResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hifz/': {
      id: '/hifz/'
      path: '/hifz'
      fullPath: '/hifz/'
      preLoaderRoute: typeof HifzIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hifz/complete': {
      id: '/hifz/complete'
      path: '/hifz/complete'
      fullPath: '/hifz/complete'
      preLoaderRoute: typeof HifzCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hifz/review': {
      id: '/hifz/review'
      path: '/hifz/review'
      fullPath: '/hifz/review'
      preLoaderRoute: typeof HifzReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hifz/session': {
      id: '/hifz/session'
      path: '/hifz/session'
      fullPath: '/hifz/session'
      preLoaderRoute: typeof HifzSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/quest': {
      id: '/home/quest'
      path: '/quest'
      fullPath: '/home/quest'
      preLoaderRoute: typeof HomeQuestRouteImport
      parentRoute: typeof HomeRoute
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/library/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/assessment': {
      id: '/onboarding/assessment'
      path: '/onboarding/assessment'
      fullPath: '/onboarding/assessment'
      preLoaderRoute: typeof OnboardingAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/avatar': {
      id: '/onboarding/avatar'
      path: '/onboarding/avatar'
      fullPath: '/onboarding/avatar'
      preLoaderRoute: typeof OnboardingAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/carousel': {
      id: '/onboarding/carousel'
      path: '/onboarding/carousel'
      fullPath: '/onboarding/carousel'
      preLoaderRoute: typeof OnboardingCarouselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/check-email': {
      id: '/onboarding/check-email'
      path: '/onboarding/check-email'
      fullPath: '/onboarding/check-email'
      preLoaderRoute: typeof OnboardingCheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dob': {
      id: '/onboarding/dob'
      path: '/onboarding/dob'
      fullPath: '/onboarding/dob'
      preLoaderRoute: typeof OnboardingDobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/forgot': {
      id: '/onboarding/forgot'
      path: '/onboarding/forgot'
      fullPath: '/onboarding/forgot'
      preLoaderRoute: typeof OnboardingForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/gateway': {
      id: '/onboarding/gateway'
      path: '/onboarding/gateway'
      fullPath: '/onboarding/gateway'
      preLoaderRoute: typeof OnboardingGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/interests': {
      id: '/onboarding/interests'
      path: '/onboarding/interests'
      fullPath: '/onboarding/interests'
      preLoaderRoute: typeof OnboardingInterestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/language': {
      id: '/onboarding/language'
      path: '/onboarding/language'
      fullPath: '/onboarding/language'
      preLoaderRoute: typeof OnboardingLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/login': {
      id: '/onboarding/login'
      path: '/onboarding/login'
      fullPath: '/onboarding/login'
      preLoaderRoute: typeof OnboardingLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/password': {
      id: '/onboarding/password'
      path: '/onboarding/password'
      fullPath: '/onboarding/password'
      preLoaderRoute: typeof OnboardingPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/reset': {
      id: '/onboarding/reset'
      path: '/onboarding/reset'
      fullPath: '/onboarding/reset'
      preLoaderRoute: typeof OnboardingResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/signup': {
      id: '/onboarding/signup'
      path: '/onboarding/signup'
      fullPath: '/onboarding/signup'
      preLoaderRoute: typeof OnboardingSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/verify': {
      id: '/onboarding/verify'
      path: '/onboarding/verify'
      fullPath: '/onboarding/verify'
      preLoaderRoute: typeof OnboardingVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/zone': {
      id: '/onboarding/zone'
      path: '/onboarding/zone'
      fullPath: '/onboarding/zone'
      preLoaderRoute: typeof OnboardingZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/': {
      id: '/play/'
      path: '/play'
      fullPath: '/play/'
      preLoaderRoute: typeof PlayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/difficulty': {
      id: '/play/difficulty'
      path: '/play/difficulty'
      fullPath: '/play/difficulty'
      preLoaderRoute: typeof PlayDifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/lobby': {
      id: '/play/lobby'
      path: '/play/lobby'
      fullPath: '/play/lobby'
      preLoaderRoute: typeof PlayLobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/topics': {
      id: '/play/topics'
      path: '/play/topics'
      fullPath: '/play/topics'
      preLoaderRoute: typeof PlayTopicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$questId': {
      id: '/quests/$questId'
      path: '/quests/$questId'
      fullPath: '/quests/$questId'
      preLoaderRoute: typeof QuestsQuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/complete': {
      id: '/quests/complete'
      path: '/quests/complete'
      fullPath: '/quests/complete'
      preLoaderRoute: typeof QuestsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/': {
      id: '/quiz/'
      path: '/'
      fullPath: '/quiz/'
      preLoaderRoute: typeof QuizIndexRouteImport
      parentRoute: typeof QuizRoute
    }
    '/quiz/results': {
      id: '/quiz/results'
      path: '/results'
      fullPath: '/quiz/results'
      preLoaderRoute: typeof QuizResultsRouteImport
      parentRoute: typeof QuizRoute
    }
  }
}

interface HomeRouteChildren {
  HomeQuestRoute: typeof HomeQuestRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeQuestRoute: HomeQuestRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

interface QuizRouteChildren {
  QuizResultsRoute: typeof QuizResultsRoute
  QuizIndexRoute: typeof QuizIndexRoute
}

const QuizRouteChildren: QuizRouteChildren = {
  QuizResultsRoute: QuizResultsRoute,
  QuizIndexRoute: QuizIndexRoute,
}

const QuizRouteWithChildren = QuizRoute._addFileChildren(QuizRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  BookmarksRoute: BookmarksRoute,
  ErrorRoute: ErrorRoute,
  HomeRoute: HomeRouteWithChildren,
  IlmbotRoute: IlmbotRoute,
  LeaderboardRoute: LeaderboardRoute,
  NotificationsRoute: NotificationsRoute,
  OfflineRoute: OfflineRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  QuizRoute: QuizRouteWithChildren,
  RamadanRoute: RamadanRoute,
  SettingsRoute: SettingsRoute,
  ShareRoute: ShareRoute,
  StoreRoute: StoreRoute,
  WalletRoute: WalletRoute,
  WisdomRoute: WisdomRoute,
  ChallengeDuelRoute: ChallengeDuelRoute,
  ChallengeResultsRoute: ChallengeResultsRoute,
  ChallengeSetupRoute: ChallengeSetupRoute,
  ChallengeWaitingRoute: ChallengeWaitingRoute,
  FriendsFriendIdRoute: FriendsFriendIdRoute,
  HalaqahGameRoute: HalaqahGameRoute,
  HalaqahResultsRoute: HalaqahResultsRoute,
  HifzCompleteRoute: HifzCompleteRoute,
  HifzReviewRoute: HifzReviewRoute,
  HifzSessionRoute: HifzSessionRoute,
  LibrarySlugRoute: LibrarySlugRoute,
  OnboardingAssessmentRoute: OnboardingAssessmentRoute,
  OnboardingAvatarRoute: OnboardingAvatarRoute,
  OnboardingCarouselRoute: OnboardingCarouselRoute,
  OnboardingCheckEmailRoute: OnboardingCheckEmailRoute,
  OnboardingDobRoute: OnboardingDobRoute,
  OnboardingForgotRoute: OnboardingForgotRoute,
  OnboardingGatewayRoute: OnboardingGatewayRoute,
  OnboardingInterestsRoute: OnboardingInterestsRoute,
  OnboardingLanguageRoute: OnboardingLanguageRoute,
  OnboardingLoginRoute: OnboardingLoginRoute,
  OnboardingPasswordRoute: OnboardingPasswordRoute,
  OnboardingResetRoute: OnboardingResetRoute,
  OnboardingSignupRoute: OnboardingSignupRoute,
  OnboardingVerifyRoute: OnboardingVerifyRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingZoneRoute: OnboardingZoneRoute,
  PlayDifficultyRoute: PlayDifficultyRoute,
  PlayLobbyRoute: PlayLobbyRoute,
  PlayTopicsRoute: PlayTopicsRoute,
  QuestsQuestIdRoute: QuestsQuestIdRoute,
  QuestsCompleteRoute: QuestsCompleteRoute,
  FriendsIndexRoute: FriendsIndexRoute,
  HalaqahIndexRoute: HalaqahIndexRoute,
  HifzIndexRoute: HifzIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  PlayIndexRoute: PlayIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
