/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CentresRouteImport } from './routes/centres'
import { Route as ChatroomsRouteImport } from './routes/chatrooms'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlayRouteImport } from './routes/play'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SponsorshipRouteImport } from './routes/sponsorship'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CentresRoute = CentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatroomsRoute = ChatroomsRouteImport.update({
  id: '/chatrooms',
  path: '/chatrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorshipRoute = SponsorshipRouteImport.update({
  id: '/sponsorship',
  path: '/sponsorship',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/centres': typeof CentresRoute
  '/chatrooms': typeof ChatroomsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/signup': typeof SignupRoute
  '/sponsorship': typeof SponsorshipRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/centres': typeof CentresRoute
  '/chatrooms': typeof ChatroomsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/signup': typeof SignupRoute
  '/sponsorship': typeof SponsorshipRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/centres': typeof CentresRoute
  '/chatrooms': typeof ChatroomsRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/play': typeof PlayRoute
  '/signup': typeof SignupRoute
  '/sponsorship': typeof SponsorshipRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/centres'
    | '/chatrooms'
    | '/events'
    | '/login'
    | '/play'
    | '/signup'
    | '/sponsorship'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/centres'
    | '/chatrooms'
    | '/events'
    | '/login'
    | '/play'
    | '/signup'
    | '/sponsorship'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/centres'
    | '/chatrooms'
    | '/events'
    | '/login'
    | '/play'
    | '/signup'
    | '/sponsorship'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CentresRoute: typeof CentresRoute
  ChatroomsRoute: typeof ChatroomsRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  PlayRoute: typeof PlayRoute
  SignupRoute: typeof SignupRoute
  SponsorshipRoute: typeof SponsorshipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centres': {
      id: '/centres'
      path: '/centres'
      fullPath: '/centres'
      preLoaderRoute: typeof CentresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatrooms': {
      id: '/chatrooms'
      path: '/chatrooms'
      fullPath: '/chatrooms'
      preLoaderRoute: typeof ChatroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsorship': {
      id: '/sponsorship'
      path: '/sponsorship'
      fullPath: '/sponsorship'
      preLoaderRoute: typeof SponsorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CentresRoute: CentresRoute,
  ChatroomsRoute: ChatroomsRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  PlayRoute: PlayRoute,
  SignupRoute: SignupRoute,
  SponsorshipRoute: SponsorshipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
